### ISSUE TITLE
missing lib directory?

### ISSUE THREAD

**Issue by XavierCLL** [george-silva/arop#1]
Hi, 

I tried compile arop in Archlinux, but this show me a error in make command:

Error: .... arop/source/lib/geolib.a: No such file or directory

In env.sh file you refer a lib directory: export MYLIB=$TOP/lib

but lib directory not exist in source code

Thanks

**Comment by george-silva** [comment]
Hello @XavierCLL !

This software is/was developed by NASA. I haven't had much experience with it, but check the orignal page for the software.

If you wish to contribute with instructions for compiling, it would be great.

http://globalchange.nasa.gov/KeywordSearch/Metadata.do?Portal=GCMD_Services&KeywordPath=ServiceParameters|DATA+ANALYSIS+AND+VISUALIZATION&EntryId=USDA_ARS_AROP&MetadataView=Full&MetadataType=1&lbnode=mdlb5

**Comment by XavierCLL** [comment]
Hi @george-silva !

Sorry I thougth you were some developer os arop :V, and I found the error, you have the source code for i386 (32bits) and I have 64bit OS, but thanks for your answer.
